name: ESLint
on:
  push:
    branches: "*"
    paths:
      - "frontend/**"
      - ".github/workflows/eslint.yml"
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '17 12 * * 4'
jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 14 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3
        working-directory: "./frontend"
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        working-directory: "./frontend"
        run: npm install

      - name: Run ESLint
        working-directory: "./frontend"
        run: npm run lint
        continue-on-error: false
