name: PyLint

on:
  pull_request:
    branches:
      - "**"
    paths:
      - "backend/**"
      - ".github/workflows/pylint.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install neccessary packages
        run: |
          python -m pip install --upgrade pip
          pip install black isort
      - name: Lint with black
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          black: true
          auto_fix: true
      - name: Sort imports
        run: |
          isort . --profile black
          git commit -am "sorted imports" || echo No isort changes to commit! 
          git push